--------------------------------------------------------------------------------
-- EduCompose Supabase Schema — README
-- 
-- Run these files IN ORDER in the Supabase SQL Editor:
--
--   1. 01_users.sql             (users + auth trigger + admin helpers)
--   2. 02_schools.sql           (schools, departments, programs_lookup)
--   3. 03_courses.sql           (courses_lookup, teacher_course_loads)
--   4. 04_teacher_loads.sql     (teacher_program_loads, blocks, block_students)
--   5. 05_students.sql          (students table)
--   6. 06_essays.sql            (essay_activities, essays, essay_analysis_results, essay_comparisons)
--   7. 07_rubrics.sql           (rubrics)
--   8. 08_notifications.sql     (notifications, activity_logs)
--   9. 09_auth.sql              (signup_verification_codes, verify_signup_code RPC)
--  10. 10_storage.sql           (storage bucket + policies)
--
-- After setup:
--   • Disable "Confirm email" in Auth → Settings (uses custom verification)
--   • Promote admin: UPDATE users SET role = 'admin' WHERE email = '...';
--------------------------------------------------------------------------------
